### ISSUE TITLE
Add User

### ISSUE THREAD

**Issue by SBorodin347** [SBorodin347/SDT_Frontend#1]
As an admin I want to add a new user to database

After navigation to add user screen from homepage, system will display two buttons:
- **Student** 
- **Teacher**

After clicking on _Student_, system will direct you to a new page with a registration form for student, that contains:
- First Name
- Last Name
- Password
- Repeating password
- Email
- Key word for resetting of password

After filling the form and clicking on button Add Student, system will add this user to database.

After clicking on _teacher_, system will direct you to a new page with a registration form for teacher, that contains:
- First Name
- Last Name
- Password
- Repeating password
- Email
- Key word for resetting of password

After filling the form and clicking on button Add Teacher, system will add this user to database.

**Comment by domiie** [comment]
**User - Student**
- [x] Button (Student)
_After clicking on Student:_
- [x] Registration form (Student)
- [x] Button (Add Student) + Functionality

**User - Teacher**
- [x] Button (Teacher)
_After clicking on Teacher:_
- [x] Registration form (Teacher)
- [x] Button (Add Teacher) + Functionality

**Comment by domiie** [comment]
Validation:

- [ ] Password and Repeating Password
- [ ] Email
- [ ] Keyword
