### ISSUE TITLE
Add subject

### ISSUE THREAD

**Issue by Gelmoxx** [SBorodin347/SDT_Frontend#10]
As a teacher I want to be able to add new subjects to the system.

After navigating to **Subjects** page, system displays button **Add Subject**. After clicking this button, system redirects **User** to new page, which contains a form with:

- Subject name
- Number of hours per week
- Number of earnable credit

Under form there's a button:
**Add Subject**

After filling the form and clicking on button **Add Subject**, system adds this subject to database and generates a specific **ID** for it.

**Comment by domiie** [comment]
- [x] Form
- [x] Button (Add Subject) + Functionality

**Comment by domiie** [comment]
Validácia
- Credit (max specified number)

**Comment by domiie** [comment]
Validácia
- [x] - Required Subject Name
- [x] - Required Hours/Week
- [x] - Required Credit
- [x]  Credit (max specified number)

**Comment by domiie** [comment]
### **FINISHED**
