### ISSUE TITLE
Remove subject

### ISSUE THREAD

**Issue by Gelmoxx** [SBorodin347/SDT_Frontend#11]
As a teacher I want to be able to remove subjects from the system.

After navigating to **Subjects** page, system displays a button **Remove Subject** next to every subject in the table. 

After clicking on **Remove Subject** system shows **Popup window** with question: "Do you really wish to delete this subject?" and two buttons:

- Yes
- No

If **User** clicks on **Yes** system removes this subject from database. 
If **User** clicks on **No** system closes popup window and nothing happens.

**Comment by domiie** [comment]
- [x] Button (Remove Subject) next to every subject
- [x] Popup Window + Functionality

**Comment by domiie** [comment]
### **FINISHED**
