### ISSUE TITLE
Edit Subject

### ISSUE THREAD

**Issue by Gelmoxx** [SBorodin347/SDT_Frontend#12]
As a teacher I want to be able to edit subjects

After navigating to **Subjects** page, system displays button **Edit Subject** next to each row. After clicking this button, system redirects **User** to a new page that contains a form with:

- Subject name
- Teacher
- Number of hours per week
- Number of earnable credits

Under form there's a button:
**Save Changes**

After filling the form and clicking on **Save Changes**, system updates the data in the database and on the website.

**Comment by domiie** [comment]
- [x] Button (Edit Subject) next to each subject
- [x] Form with specified inputs
- [x] Button (Save Changes) that updates the DB

**Comment by domiie** [comment]
### **FINISHED**
