### ISSUE TITLE
Edit User

### ISSUE THREAD

**Issue by Gelmoxx** [SBorodin347/SDT_Frontend#2]
As an admin I want to be able to edit user's information.
After navigating to add user screen from homepage, system will display an Edit User button.

Clicking the button will cause system to fill out the form with current information
- First Name
- Last Name
- Password
- Email
- Key word for resetting of password

After changing information in the form and clicking Save Changes button, system will update information in the database and on the website.

**Comment by domiie** [comment]
- [x] Button (Edit User) + Functionality
- [x] Button (Save Changes) + Functionality
