### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by Gelmoxx** [SBorodin347/SDT_Frontend#3]
As an admin I want to be able to delete a user from database.

After navigation to Delete User screen from homepage, system will display a table with user information and a Delete User button.
After clicking the button, system will display a pop-up window with a confirmation question "Are you sure you want to delete the user?" and two options:
- Confirm
- Cancel

After clicking the Confirm option, system will remove the user from the database and the shown table.

**Comment by domiie** [comment]
- [x] Button (Delete User) + Functionality
- [x] Pop-up window with option + Functionality
